version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: petinova_postgres
    restart: always
    environment:
      POSTGRES_DB: petinova_db
      POSTGRES_USER: petinova_user
      POSTGRES_PASSWORD: petinova_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petinova_user -d petinova_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer:latest
    container_name: petinova_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data: